require'lspconfig'.vuels.setup{}
require'lspconfig'.tsserver.setup{}
require'lspconfig'.dartls.setup{}
require'lspconfig'.html.setup{}
require'lspconfig'.cssls.setup{}
require'lspconfig'.cssmodules_ls.setup{}
require'lspconfig'.yamlls.setup{}
require'lspconfig'.jsonls.setup{}
require'lspconfig'.dockerls.setup{}
require'lspconfig'.vimls.setup{}
